name: facerecognition
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.1
  image_picker: ^0.8.7+4
  fluttertoast: ^8.2.1
  firebase_storage: ^11.2.0
  google_mlkit_face_detection: ^0.5.0
  flutter_native_image: ^0.0.6+1
  tflite_flutter_helper: 
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  camera: ^0.8.1+3
  
  image: ^3.3.0
  excel: ^2.1.0
  path_provider: ^2.0.15
  open_file: ^3.0.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/facenet.tflite
    - assets/mobile_face_net.tflite
    - assets/images/log1.png
    - assets/images/logo.png
    - assets/images/profile.png
