name: facerecognition
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.1
  image_picker: ^0.8.7+4
  fluttertoast: ^8.2.1
  firebase_storage: ^11.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/log1.png
    - assets/images/logo.png
    - assets/images/profile.png
